[project]
scalaVersion   = "2.13.1"
scalaJsVersion = "1.0.1"
scalaOptions   = [
  "-encoding", "UTF-8",
  "-unchecked",
  "-deprecation",
  "-Xfuture",
  "-Ywarn-numeric-widen",
  "-feature"
]
testFrameworks = [
  "org.scalatest.tools.Framework"
]

[module.translit]
root    = "shared"
sources = ["shared/src/main/scala"]
targets = ["js", "jvm"]

[module.translit.jvm]
root = "jvm"

[module.translit.test]
sources   = ["shared/src/test/scala"]
targets   = ["js", "jvm"]
scalaDeps = [
  ["org.scalatest", "scalatest", "3.1.1"]
]

[module.translit.test.jvm]
sources   = ["jvm/src/test/scala"]
scalaDeps = [
  ["com.github.pathikrit", "better-files", "3.9.1"],
  ["org.scalaj", "scalaj-http", "2.4.2"]
]
